### ISSUE TITLE
pip install immutable isn't working

### ISSUE THREAD

**Issue by andrefarzat** [theengineear/immutable#1]
<img width="698" alt="screen shot 2015-11-14 at 10 48 24 pm" src="https://cloud.githubusercontent.com/assets/649219/11167090/e63de2c4-8b21-11e5-99e0-e9536718dc04.png">

:sob:

**Comment by theengineear** [comment]
Ha. I'll put it back up today. I actually made some changes to it to support the Python Sequence _and_ Mapping APIs. Sorta a cute hack.

@andrefarzat how goes? : D

**Comment by theengineear** [comment]
@andrefarzat should be working now :) The old `ImmutableFactory` stuff is there. But I made some improvements to allow nested, immutable objects too, the catch is that no values can be mutable. That's in the new `Immutable` class.

**Comment by andrefarzat** [comment]
yeah! It worked. Nice job making it a simple class! 

Thank you :smile_cat:
